### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by onyxarchitect** [s-shin/linter-perl#14]
Can someone please point me to documents on how to use this plug in?

Will I see the feedback in the Atom editor when I open any perl file or I need to run a particular command in DOS console? What would be the command?  gulp lint?  

PS I am using Windows Active State Perl. (This is perl 5, version 20, subversion 2 (v5.20.2) built for MSWin32-x64-multi-thread).

**Comment by s-shin** [comment]
OK, but I'm afraid that sufficient information may not be given because I'm not a Windows user.
Also this package have not been tested in Windows at all, so that I welcome any feedback or pull requests anytime!

First of all, you need install [linter package](https://atom.io/packages/linter) since this package is just based on it. Did you do that?

Then you may have to update the "PATH" environment variable of Windows or set a path to "executablePath" in the linter-perl options (you can do this in "config.cson" or the setting view). 
(In fact, the perl interpreter can be easily detected in UNIX like OS, but since Windows is not an UNIX, the node runtime in Atom cannot find the interpreter with no hint.)

Finally, open a perl source in Atom. Without special commands, you will get linted results (if there are errors) when you press any key or save the document.

That's all. Good luck :)
